identifier = "default"
description = "Default permissions for main window"
local = true
windows = ["main"]
urls = ["local", "http://localhost:*", "http://127.0.0.1:*", "http://localhost:5173", "http://localhost:5174", "http://localhost:5175", "http://localhost:5176"]
permissions = [
  "core:default",
  "core:event:allow-listen",
  "core:event:allow-emit",
  "core:event:allow-emit-to",
  "store:default"
]
