name: Tauri Cross-Platform 4

on:
  push:
    tags:
      - "v*.*.*"
  workflow_dispatch:

jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-22.04, windows-latest, macos-latest]
        include:
          - os: macos-latest
            rust-target: x86_64-apple-darwin
          - os: ubuntu-22.04
            rust-target: x86_64-unknown-linux-gnu
          - os: windows-latest
            rust-target: x86_64-pc-windows-msvc

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 18

      - name: Setup Rust
        uses: dtolnay/rust-toolchain@stable
        with:
          toolchain: stable
          targets: ${{ matrix.rust-target }}

      - name: Cache cargo
        uses: actions/cache@v3
        with:
          path: |
            ~/.cargo/registry
            ~/.cargo/git
            src-tauri/target
          key: ${{ runner.os }}-cargo-${{ hashFiles('**/Cargo.lock') }}

      - name: Install Linux dependencies
        if: matrix.os == 'ubuntu-22.04'
        run: |
          sudo apt-get update -y
          sudo apt-get install -y \
            libwebkit2gtk-4.1-dev \
            build-essential \
            libgtk-3-dev \
            libayatana-appindicator3-dev

      - name: Install Windows dependencies
        if: matrix.os == 'windows-latest'
        run: |
          # Install Chocolatey if not present
          Set-ExecutionPolicy Bypass -Scope Process -Force
          [System.Net.ServicePointManager]::SecurityProtocol = [System.Net.ServicePointManager]::SecurityProtocol -bor 3072
          iex ((New-Object System.Net.WebClient).DownloadString('https://community.chocolatey.org/install.ps1'))
          
          # Refresh PATH
          $env:Path = [System.Environment]::GetEnvironmentVariable("Path","Machine") + ";" + [System.Environment]::GetEnvironmentVariable("Path","User")
          
          # Install dependencies with specific versions
          choco install -y nodejs-lts --version=18.17.1
          choco install -y python --version=3.10.11
          choco install -y vcredist2015

      - name: Prepare macOS environment
        if: matrix.os == 'macos-latest'
        run: |
          brew update || true
          brew upgrade || true
          brew doctor || true

      - name: Install macOS dependencies
        if: matrix.os == 'macos-latest'
        run: |
          brew install cmake pkg-config || true
          brew install gtk+3 webkitgtk libsoup || true
          brew install libayatana-appindicator || true
          brew link --overwrite libayatana-appindicator || true
          brew upgrade cmake gtk+3 webkitgtk libsoup libayatana-appindicator || true

      - name: Verify macOS environment
        if: matrix.os == 'macos-latest'
        run: |
          echo "Checking installed versions:"
          pkg-config --modversion gtk+-3.0 || echo "GTK not found"
          pkg-config --modversion webkitgtk-4.0 || echo "WebKitGTK not found"
          pkg-config --modversion libayatana-appindicator-3.0 || echo "AppIndicator not found"
          
          echo "Library paths:"
          ls -la /opt/homebrew/lib/pkgconfig/ | grep gtk || true
          ls -la /opt/homebrew/lib/pkgconfig/ | grep webkit || true
          ls -la /opt/homebrew/lib/pkgconfig/ | grep ayatana || true

      - name: Install npm dependencies
        run: npm install

      - name: Build Tauri app
        run: npm run tauri build

      - name: Upload artifacts
        uses: actions/upload-artifact@v4
        with:
          name: tauri-${{ matrix.os }}-build
          path: |
            src-tauri/target/release/*.deb
            src-tauri/target/release/*.AppImage
            src-tauri/target/release/*.msi
            src-tauri/target/release/*.dmg
            src-tauri/target/release/*.pkg
