name: Tauri Cross-Platform Build

on:
  push:
    tags:
      - "v*.*.*"
  workflow_dispatch:

jobs:
  ubuntu-build:
    name: Build on Ubuntu
    runs-on: ubuntu-22.04

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 18

      - name: Setup Rust
        uses: dtolnay/rust-toolchain@stable
        with:
          toolchain: stable
          targets: x86_64-unknown-linux-gnu

      - name: Install Linux dependencies
        run: |
          sudo apt update
          sudo apt install -y \
            build-essential \
            curl \
            wget \
            libssl-dev \
            libgtk-3-dev \
            libwebkit2gtk-4.0-dev \
            libsoup2.4-dev \
            libjavascriptcoregtk-4.0-dev \
            libayatana-appindicator3-dev \
            libappindicator3-dev \
            librsvg2-dev \
            patchelf \
            pkg-config

      - name: Install npm dependencies
        run: npm install

      - name: Build Tauri app
        run: npm run tauri build

      - name: Upload Linux Artifacts
        uses: actions/upload-artifact@v4
        with:
          name: tauri-linux
          path: |
            src-tauri/target/release/bundle/**/*.deb
            src-tauri/target/release/bundle/**/*.AppImage

  macos-build:
    name: Build on macOS
    runs-on: macos-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 18

      - name: Setup Rust
        uses: dtolnay/rust-toolchain@stable
        with:
          toolchain: stable
          targets: x86_64-apple-darwin

      - name: Install macOS dependencies
        run: |
          brew update
          brew install cmake pkg-config gtk+3 libsoup
          brew install libayatana-appindicator || true

      - name: Install npm dependencies
        run: npm install

      - name: Build Tauri app
        run: npm run tauri build

      - name: Upload macOS Artifacts
        uses: actions/upload-artifact@v4
        with:
          name: tauri-macos
          path: |
            src-tauri/target/release/bundle/dmg/*.dmg
            src-tauri/target/release/bundle/osx/*.pkg

  windows-build:
    name: Build on Windows
    runs-on: windows-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 18

      - name: Setup Rust
        uses: dtolnay/rust-toolchain@stable
        with:
          toolchain: stable
          targets: x86_64-pc-windows-msvc

      - name: Install Windows dependencies
        run: |
          choco install -y nodejs-lts --version=18.17.1
          choco install -y python --version=3.10.11
          choco install -y vcredist2015

      - name: Install npm dependencies
        run: npm install

      - name: Build Tauri app
        run: npm run tauri build

      - name: Upload Windows Artifacts
        uses: actions/upload-artifact@v4
        with:
          name: tauri-windows
          path: |
            src-tauri/target/release/bundle/msi/*.msi

  release:
    name: Create GitHub Release
    needs: [ubuntu-build, macos-build, windows-build]
    if: startsWith(github.ref, 'refs/tags/')
    runs-on: ubuntu-latest

    steps:
      - name: Download all artifacts
        uses: actions/download-artifact@v4
        with:
          path: ./artifacts

      - name: Create GitHub Release
        uses: softprops/action-gh-release@v1
        with:
          name: Release ${{ github.ref_name }}
          body: |
            ### Release ${{ github.ref_name }}
            - ✅ Cross-platform builds (Windows, macOS, Linux)
            - 🔄 Built from tag ${{ github.ref_name }}
          files: ./artifacts/**/*.*
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
