name: Tauri Cross-Platform Build

on:
  push:
    tags:
      - "v*.*.*"
  workflow_dispatch:

jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-22.04, windows-latest, macos-latest]
        include:
          - os: macos-latest
            rust-target: x86_64-apple-darwin
          - os: ubuntu-22.04
            rust-target: x86_64-unknown-linux-gnu
          - os: windows-latest
            rust-target: x86_64-pc-windows-msvc

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 18

      - name: Setup Rust
        uses: dtolnay/rust-toolchain@stable
        with:
          toolchain: stable
          targets: ${{ matrix.rust-target }}

      - name: Cache cargo
        uses: actions/cache@v3
        with:
          path: |
            ~/.cargo/registry
            ~/.cargo/git
            src-tauri/target
          key: ${{ runner.os }}-cargo-${{ hashFiles('**/Cargo.lock') }}

      - name: Install Linux dependencies
        if: matrix.os == 'ubuntu-22.04'
        run: |
          sudo apt-get update -y
          sudo apt-get install -y \
            libwebkit2gtk-4.0-dev \
            build-essential \
            libgtk-3-dev \
            libayatana-appindicator3-dev \
            libsoup2.4-dev

      - name: Install Windows dependencies
        if: matrix.os == 'windows-latest'
        uses: actions/setup-python@v5
        with:
          python-version: 3.10

      - name: Setup macOS dependencies
        if: matrix.os == 'macos-latest'
        run: |
          brew update
          brew install cmake pkg-config gtk+3 libsoup || true

      - name: Install Tauri CLI
        run: npm install @tauri-apps/cli

      - name: Install npm dependencies
        run: npm install

      - name: Build Tauri app
        run: npx tauri build

      - name: Verify build outputs
        run: |
          echo "Build artifacts:"
          find src-tauri/target/release/bundle -type f || true

      - name: Upload artifacts
        uses: actions/upload-artifact@v4
        with:
          name: tauri-${{ matrix.os }}-build
          path: |
            src-tauri/target/release/bundle/**/*.deb
            src-tauri/target/release/bundle/**/*.AppImage
            src-tauri/target/release/bundle/**/*.msi
            src-tauri/target/release/bundle/**/*.dmg
            src-tauri/target/release/bundle/**/*.pkg

      - name: Create Release
        if: success() && startsWith(github.ref, 'refs/tags/')
        uses: softprops/action-gh-release@v1
        with:
          name: Release ${{ github.ref_name }}
          body: |
            ### Release ${{ github.ref_name }}
            - Built for Windows, macOS, and Linux
            - See commit history for changes
          files: |
            src-tauri/target/release/bundle/**/*.deb
            src-tauri/target/release/bundle/**/*.AppImage
            src-tauri/target/release/bundle/**/*.msi
            src-tauri/target/release/bundle/**/*.dmg
            src-tauri/target/release/bundle/**/*.pkg
          draft: false
          prerelease: false
