name: Tauri Build

on:
  push:
    tags:
      - "v*.*.*"

jobs:
  build:
    runs-on: ubuntu-22.04  # Using LTS version for stability

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 18

      - name: Setup Rust
        uses: dtolnay/rust-toolchain@stable
        with:
          toolchain: stable
          targets: x86_64-unknown-linux-gnu

      - name: Install GLib with Absolute Path Guarantee
        run: |
          # Complete system cleanup
          sudo apt-get remove -y libglib2.0-dev libgobject-2.0-dev libgio-2.0-dev || true
          sudo apt-get autoremove -y
          sudo rm -f /usr/lib/x86_64-linux-gnu/pkgconfig/{glib,gobject,gio}-2.0.pc
          sudo rm -f /usr/share/pkgconfig/{glib,gobject,gio}-2.0.pc

          # Install specific versions with dependencies
          sudo apt-get update -y
          sudo apt-get install -y \
            libglib2.0-dev=2.72.4-0ubuntu2 \
            libgobject-2.0-dev=2.72.4-0ubuntu2 \
            libgio-2.0-dev=2.72.4-0ubuntu2 \
            libgtk-3-dev \
            libwebkit2gtk-4.0-dev \
            pkg-config \
            build-essential \
            libssl-dev

          # Create explicit symlinks
          sudo mkdir -p /usr/share/pkgconfig
          sudo ln -sf /usr/lib/x86_64-linux-gnu/pkgconfig/glib-2.0.pc /usr/share/pkgconfig/
          sudo ln -sf /usr/lib/x86_64-linux-gnu/pkgconfig/gobject-2.0.pc /usr/share/pkgconfig/
          sudo ln -sf /usr/lib/x86_64-linux-gnu/pkgconfig/gio-2.0.pc /usr/share/pkgconfig/
          sudo ldconfig

          # Set exhaustive environment variables
          echo "PKG_CONFIG_PATH=/usr/lib/x86_64-linux-gnu/pkgconfig:/usr/share/pkgconfig" >> $GITHUB_ENV
          echo "LD_LIBRARY_PATH=/usr/lib/x86_64-linux-gnu" >> $GITHUB_ENV

      - name: Verify GLib Installation
        run: |
          echo "=== GLib Verification ==="
          echo "GLib version: $(pkg-config --modversion glib-2.0)"
          echo "GObject version: $(pkg-config --modversion gobject-2.0)"
          echo "File locations:"
          ls -la /usr/lib/x86_64-linux-gnu/pkgconfig/glib-2.0.pc
          ls -la /usr/share/pkgconfig/glib-2.0.pc
          
          if ! pkg-config --exists glib-2.0; then
            echo "::error::GLib still not found after installation"
            exit 1
          fi

      - name: Install npm dependencies
        run: npm install

      - name: Build Tauri App
        run: |
          export PKG_CONFIG_PATH=/usr/lib/x86_64-linux-gnu/pkgconfig:/usr/share/pkgconfig
          export LD_LIBRARY_PATH=/usr/lib/x86_64-linux-gnu
          npm run tauri build

      - name: Upload artifacts
        uses: actions/upload-artifact@v4
        with:
          name: tauri-build
          path: src-tauri/target/release/
