name: Tauri Cross-Platform Build

on:
  push:
    tags:
      - "v*.*.*"

jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-22.04, windows-latest, macos-latest]
        include:
          - os: macos-latest
            rust-target: x86_64-apple-darwin
          - os: ubuntu-22.04
            rust-target: x86_64-unknown-linux-gnu
          - os: windows-latest
            rust-target: x86_64-pc-windows-msvc

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 18

      - name: Setup Rust
        uses: dtolnay/rust-toolchain@stable
        with:
          toolchain: stable
          targets: ${{ matrix.rust-target }}

      - name: Install Linux dependencies
        if: matrix.os == 'ubuntu-22.04'
        run: |
          sudo apt-get update -y
          sudo apt-get install -y \
            build-essential \
            libssl-dev \
            libffi-dev \
            libmount-dev \
            zlib1g-dev \
            gettext \
            cmake \
            ninja-build \
            meson \
            libgtk-3-dev \
            libwebkit2gtk-4.1-dev \
            libsoup-3.0-dev \
            libayatana-appindicator3-dev \
            librsvg2-dev \
            patchelf \
            pkg-config

      - name: Install Windows dependencies
        if: matrix.os == 'windows-latest'
        run: |
          choco install -y nodejs.install python --version=3.11.5 mingw

      - name: Install macOS dependencies (with Homebrew fixes)
        if: matrix.os == 'macos-latest'
        run: |
          # Reset Homebrew to avoid tap issues
          brew update-reset
          brew update
          
          # Install required dependencies
          brew install cmake pkg-config
          brew install gtk+3 webkitgtk libsoup
          brew install libayatana-appindicator
          
          # Fix potential linking issues
          brew link --overwrite libayatana-appindicator
          
          # Verify installations
          brew list --versions gtk+3 webkitgtk libsoup libayatana-appindicator

      - name: Install npm dependencies
        run: npm install

      - name: Build Tauri app
        run: npm run tauri build

      - name: Upload artifacts
        uses: actions/upload-artifact@v4
        if: success()
        with:
          name: tauri-${{ matrix.os }}-build
          path: |
            src-tauri/target/release/*.deb
            src-tauri/target/release/*.AppImage
            src-tauri/target/release/*.msi
            src-tauri/target/release/*.dmg
            src-tauri/target/release/*.pkg
            src-tauri/target/release/*.zip
            src-tauri/target/release/*.tar.gz
