name: Build Tauri App

on:
  push:
    tags:
      - "v*.*.*"

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20

      - name: Setup Rust
        uses: dtolnay/rust-toolchain@stable
        with:
          toolchain: stable

      - name: Nuclear GLib Installation
        run: |
          # Complete system cleanup
          sudo apt-get remove -y libglib2.0-* libgobject-* libgio-* || true
          sudo apt-get autoremove -y
          sudo find /usr -name "*glib*" -delete 2>/dev/null || true
          sudo find /usr -name "*gobject*" -delete 2>/dev/null || true
          sudo find /usr -name "*gio*" -delete 2>/dev/null || true

          # Install from fresh with all possible variants
          sudo apt-get update -y
          sudo apt-get install -y \
            libglib2.0-dev \
            libglib2.0-dev-bin \
            libgirepository1.0-dev \
            libgobject-2.0-dev \
            libgio-2.0-dev \
            libgtk-3-dev \
            libwebkit2gtk-4.0-dev \
            pkg-config \
            build-essential

          # Force-create symlinks in all possible locations
          sudo mkdir -p /usr/share/pkgconfig /usr/local/lib/pkgconfig
          sudo ln -sf /usr/lib/x86_64-linux-gnu/pkgconfig/glib-2.0.pc /usr/share/pkgconfig/
          sudo ln -sf /usr/lib/x86_64-linux-gnu/pkgconfig/glib-2.0.pc /usr/local/lib/pkgconfig/
          sudo ldconfig

          # Set exhaustive environment paths
          echo "PKG_CONFIG_PATH=/usr/lib/x86_64-linux-gnu/pkgconfig:/usr/share/pkgconfig:/usr/local/lib/pkgconfig:/usr/lib/pkgconfig" >> $GITHUB_ENV
          echo "LD_LIBRARY_PATH=/usr/lib/x86_64-linux-gnu:/usr/local/lib" >> $GITHUB_ENV
          echo "GI_TYPELIB_PATH=/usr/lib/x86_64-linux-gnu/girepository-1.0" >> $GITHUB_ENV

      - name: Verify Installation
        run: |
          echo "=== Nuclear Verification ==="
          echo "GLib version: $(pkg-config --modversion glib-2.0 || echo 'FAILED')"
          echo "GObject version: $(pkg-config --modversion gobject-2.0 || echo 'FAILED')"
          echo "GIO version: $(pkg-config --modversion gio-2.0 || echo 'FAILED')"
          
          echo "All glib-2.0.pc locations:"
          sudo find /usr -name "glib-2.0.pc" 2>/dev/null || echo "NONE FOUND"
          
          if ! pkg-config --exists glib-2.0; then
            echo "::error::CRITICAL FAILURE: GLib still not found after nuclear installation"
            echo "::error::This suggests a fundamental system issue - consider using a different base image"
            exit 1
          fi

      - name: Build Tauri App
        run: |
          # Hardcode paths as final fallback
          export PKG_CONFIG_PATH=/usr/lib/x86_64-linux-gnu/pkgconfig:/usr/share/pkgconfig
          export LD_LIBRARY_PATH=/usr/lib/x86_64-linux-gnu
          npm run tauri build

      - name: Upload artifacts
        uses: actions/upload-artifact@v4
        with:
          name: tauri-build
          path: src-tauri/target/release/
