name: Build and Release Tauri App

on:
  push:
    tags:
      - "v*.*.*"

jobs:
  build:
    strategy:
      matrix:
        platform: [ubuntu-latest]
    runs-on: ${{ matrix.platform }}

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20

      - name: Setup Rust
        uses: dtolnay/rust-toolchain@stable
        with:
          toolchain: stable

      - name: Install GLib and dependencies (Nuclear Option)
        run: |
          sudo apt-get update -y
          # Remove any potentially broken installations
          sudo apt-get remove -y libglib2.0-dev || true
          sudo apt-get autoremove -y
          
          # Install with all possible variants
          sudo apt-get install -y \
            libglib2.0-dev \
            libglib2.0-dev-bin \
            gir1.2-glib-2.0 \
            libglib2.0-0 \
            libglib2.0-doc \
            pkg-config \
            build-essential

          # Force install from source if still missing
          if ! pkg-config --exists glib-2.0; then
            echo "::warning::GLib not found, installing from source"
            wget https://download.gnome.org/sources/glib/2.70/glib-2.70.0.tar.xz
            tar -xf glib-2.70.0.tar.xz
            cd glib-2.70.0
            meson setup _build
            ninja -C _build
            sudo ninja -C _build install
            sudo ldconfig
          fi

          # Find and verify glib installation
          GLIB_PC_PATH=$(find /usr -name "glib-2.0.pc" 2>/dev/null | head -1)
          if [ -z "$GLIB_PC_PATH" ]; then
            echo "::error::glib-2.0.pc not found after installation!"
            exit 1
          fi

          echo "GLib version: $(pkg-config --modversion glib-2.0)"
          echo "GLib path: $GLIB_PC_PATH"
          echo "PKG_CONFIG_PATH=$(dirname $GLIB_PC_PATH):/usr/lib/x86_64-linux-gnu/pkgconfig:/usr/share/pkgconfig:/usr/local/lib/pkgconfig" >> $GITHUB_ENV
          echo "LD_LIBRARY_PATH=/usr/local/lib:/usr/lib/x86_64-linux-gnu" >> $GITHUB_ENV

      - name: Install remaining Tauri dependencies
        run: |
          sudo apt-get install -y \
            libwebkit2gtk-4.0-dev \
            libgtk-3-dev \
            libssl-dev \
            libayatana-appindicator3-dev \
            librsvg2-dev

      - name: Verify environment
        run: |
          echo "=== Environment Verification ==="
          pkg-config --list-all | grep glib
          pkg-config --modversion glib-2.0
          pkg-config --cflags --libs glib-2.0
          echo "PKG_CONFIG_PATH: $PKG_CONFIG_PATH"
          echo "LD_LIBRARY_PATH: $LD_LIBRARY_PATH"

      - name: Install npm dependencies
        run: |
          npm install
          npm run build

      - name: Build Tauri app
        run: |
          export PKG_CONFIG_PATH=$PKG_CONFIG_PATH
          export LD_LIBRARY_PATH=$LD_LIBRARY_PATH
          npm run tauri build

      - name: Upload artifacts
        uses: actions/upload-artifact@v4
        with:
          name: tauri-build
          path: src-tauri/target/release/
