name: Build Tauri App

on:
  push:
    tags:
      - "v*.*.*"

jobs:
  build:
    strategy:
      matrix:
        platform: [ubuntu-latest, macos-latest, windows-latest]
    runs-on: ${{ matrix.platform }}

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20

      - name: Setup Rust
        uses: dtolnay/rust-toolchain@stable
        with:
          toolchain: stable
          targets: ${{ runner.os == 'Linux' && 'x86_64-unknown-linux-gnu' || '' }}

      # Linux-specific setup
      - name: Linux - Nuclear Dependency Installation
        if: runner.os == 'Linux'
        run: |
          # Complete cleanup
          sudo apt-get remove -y libglib2.0-* libgobject-* libgio-* || true
          sudo apt-get autoremove -y
          sudo find /usr -name "*glib*" -delete 2>/dev/null || true
          sudo find /usr -name "*gobject*" -delete 2>/dev/null || true
          sudo find /usr -name "*gio*" -delete 2>/dev/null || true

          # Install specific known-working versions
          sudo apt-get update -y
          sudo apt-get install -y \
            libglib2.0-dev=2.72.4-0ubuntu2 \
            libgirepository1.0-dev=1.72.0-1 \
            libgobject-2.0-dev=2.72.4-0ubuntu2 \
            libgio-2.0-dev=2.72.4-0ubuntu2 \
            libgtk-3-dev=3.24.33-1ubuntu2 \
            libwebkit2gtk-4.0-dev=2.38.5-0ubuntu0.22.04.1 \
            pkg-config=0.29.2-1ubuntu3 \
            build-essential=12.9ubuntu3

          # Force-create symlinks
          sudo mkdir -p /usr/share/pkgconfig /usr/local/lib/pkgconfig
          sudo ln -sf /usr/lib/x86_64-linux-gnu/pkgconfig/glib-2.0.pc /usr/share/pkgconfig/
          sudo ln -sf /usr/lib/x86_64-linux-gnu/pkgconfig/gobject-2.0.pc /usr/share/pkgconfig/
          sudo ln -sf /usr/lib/x86_64-linux-gnu/pkgconfig/gio-2.0.pc /usr/share/pkgconfig/
          sudo ldconfig

          echo "PKG_CONFIG_PATH=/usr/lib/x86_64-linux-gnu/pkgconfig:/usr/share/pkgconfig:/usr/local/lib/pkgconfig" >> $GITHUB_ENV
          echo "LD_LIBRARY_PATH=/usr/lib/x86_64-linux-gnu:/usr/local/lib" >> $GITHUB_ENV

      # macOS-specific setup
      - name: macOS - Install GTK Stack
        if: runner.os == 'macOS'
        run: |
          brew update
          brew install pkg-config gtk+3 webkit2gtk librsvg
          brew link --overwrite gtk+3
          echo "PKG_CONFIG_PATH=$(brew --prefix)/lib/pkgconfig" >> $GITHUB_ENV

      # Windows-specific setup
      - name: Windows - Install Build Tools
        if: runner.os == 'Windows'
        run: |
          choco install -y visualstudio2022-workload-vctools
          refreshenv

      - name: Verify Dependencies
        run: |
          if [[ "$RUNNER_OS" == "Linux" ]]; then
            echo "=== Linux Verification ==="
            pkg-config --modversion glib-2.0 || echo "::error::GLib not found"
            pkg-config --modversion gobject-2.0 || echo "::error::GObject not found"
            pkg-config --modversion gio-2.0 || echo "::error::GIO not found"
            echo "PKG_CONFIG_PATH: $PKG_CONFIG_PATH"
          elif [[ "$RUNNER_OS" == "macOS" ]]; then
            echo "=== macOS Verification ==="
            brew list gtk+3 || echo "::error::GTK not found"
            brew list webkit2gtk || echo "::error::WebKitGTK not found"
          else
            echo "=== Windows Verification ==="
            cl.exe /? > nul || echo "::error::Visual Studio tools not found"
          fi

      - name: Install npm dependencies
        run: npm install

      - name: Build Tauri App
        env:
          PKG_CONFIG_PATH: ${{ runner.os == 'Linux' && '/usr/lib/x86_64-linux-gnu/pkgconfig:/usr/share/pkgconfig:/usr/local/lib/pkgconfig' || runner.os == 'macOS' && '$(brew --prefix)/lib/pkgconfig' || '' }}
          LD_LIBRARY_PATH: ${{ runner.os == 'Linux' && '/usr/lib/x86_64-linux-gnu:/usr/local/lib' || '' }}
        run: npm run tauri build

      - name: Upload artifacts
        uses: actions/upload-artifact@v4
        with:
          name: tauri-build-${{ runner.os }}
          path: |
            src-tauri/target/release/*.deb
            src-tauri/target/release/*.AppImage
            src-tauri/target/release/*.tar.gz
            src-tauri/target/release/*.msi
            src-tauri/target/release/*.exe
