name: Tauri Cross-Platform Build

on:
  push:
    tags:
      - "v*.*.*"

jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-22.04, windows-latest, macos-latest]

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 18

      - name: Setup Rust
        uses: dtolnay/rust-toolchain@stable
        with:
          toolchain: stable
          targets: x86_64-unknown-linux-gnu

      - name: Cache cargo
        uses: actions/cache@v3
        with:
          path: |
            ~/.cargo/registry
            ~/.cargo/git
            src-tauri/target
          key: ${{ runner.os }}-cargo-${{ hashFiles('**/Cargo.lock') }}

      - name: Install Linux dependencies
        if: matrix.os == 'ubuntu-22.04'
        run: |
          sudo apt-get update -y
          sudo apt-get install -y \
            libwebkit2gtk-4.1-dev \
            build-essential \
            libgtk-3-dev \
            libayatana-appindicator3-dev

      - name: Install Windows dependencies
        if: matrix.os == 'windows-latest'
        run: |
          choco install -y nodejs python --version=3.11.5

      - name: Install macOS dependencies
        if: matrix.os == 'macos-latest'
        run: |
          brew cleanup
          brew update
          brew install cmake pkg-config gtk+3 webkitgtk libsoup
          brew install libayatana-appindicator
          brew link --overwrite libayatana-appindicator

      - name: Verify macOS Environment
        if: matrix.os == 'macos-latest'
        run: |
          pkg-config --modversion gtk+-3.0
          pkg-config --modversion webkitgtk-4.0
          pkg-config --modversion libayatana-appindicator-3.0

      - name: Install npm dependencies
        run: npm install

      - name: Build Tauri app
        run: npm run tauri build

      - name: Upload artifacts
        uses: actions/upload-artifact@v4
        with:
          name: tauri-${{ matrix.os }}-build
          path: |
            src-tauri/target/release/*.deb
            src-tauri/target/release/*.AppImage
            src-tauri/target/release/*.msi
            src-tauri/target/release/*.dmg
            src-tauri/target/release/*.pkg
