name: Build Tauri App

on:
  push:
    tags:
      - "v*.*.*"

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20

      - name: Setup Rust
        uses: dtolnay/rust-toolchain@stable
        with:
          toolchain: stable

      - name: Install GLib with Nuclear Option
        run: |
          # Completely remove existing installations
          sudo apt-get remove -y libglib2.0-dev libgobject-2.0-dev libgio-2.0-dev || true
          sudo apt-get autoremove -y
          sudo rm -f /usr/lib/x86_64-linux-gnu/pkgconfig/glib-2.0.pc \
                    /usr/share/pkgconfig/glib-2.0.pc \
                    /usr/local/lib/pkgconfig/glib-2.0.pc || true
          
          # Install with all possible variants
          sudo apt-get update -y
          sudo apt-get install -y \
            libglib2.0-dev \
            libglib2.0-dev-bin \
            libgirepository1.0-dev \
            libgobject-2.0-dev \
            libgio-2.0-dev \
            libgtk-3-dev \
            libwebkit2gtk-4.0-dev \
            pkg-config \
            build-essential

          # Force reinstall if files are missing
          if [ ! -f "/usr/lib/x86_64-linux-gnu/pkgconfig/glib-2.0.pc" ]; then
            echo "::warning::GLib not found, reinstalling..."
            sudo apt-get install --reinstall -y libglib2.0-dev
          fi

          # Create guaranteed symlinks
          sudo mkdir -p /usr/share/pkgconfig
          sudo ln -sf /usr/lib/x86_64-linux-gnu/pkgconfig/glib-2.0.pc /usr/share/pkgconfig/ || true
          sudo ln -sf /usr/lib/x86_64-linux-gnu/pkgconfig/gobject-2.0.pc /usr/share/pkgconfig/ || true
          sudo ln -sf /usr/lib/x86_64-linux-gnu/pkgconfig/gio-2.0.pc /usr/share/pkgconfig/ || true

          # Set exhaustive environment variables
          echo "PKG_CONFIG_PATH=/usr/lib/x86_64-linux-gnu/pkgconfig:/usr/share/pkgconfig:/usr/local/lib/pkgconfig:/usr/lib/pkgconfig" >> $GITHUB_ENV
          echo "LD_LIBRARY_PATH=/usr/lib/x86_64-linux-gnu:/usr/local/lib" >> $GITHUB_ENV

      - name: Verify GLib Installation
        run: |
          echo "=== Nuclear Verification ==="
          echo "GLib version: $(pkg-config --modversion glib-2.0 || echo 'NOT FOUND')"
          echo "GObject version: $(pkg-config --modversion gobject-2.0 || echo 'NOT FOUND')"
          echo "GIO version: $(pkg-config --modversion gio-2.0 || echo 'NOT FOUND')"
          echo "All glib-2.0.pc locations:"
          sudo find /usr -name "glib-2.0.pc" 2>/dev/null || echo "NONE FOUND"
          echo "PKG_CONFIG_PATH: $PKG_CONFIG_PATH"
          
          if ! pkg-config --exists glib-2.0; then
            echo "::error::GLib still not found after nuclear installation!"
            exit 1
          fi

      - name: Install npm dependencies
        run: npm install

      - name: Build Tauri App
        run: |
          # Explicitly set all paths
          export PKG_CONFIG_PATH=$PKG_CONFIG_PATH
          export LD_LIBRARY_PATH=$LD_LIBRARY_PATH
          npm run tauri build

      - name: Upload artifacts
        uses: actions/upload-artifact@v4
        with:
          name: tauri-build
          path: src-tauri/target/release/
