name: Build and Release Tauri App

on:
  push:
    tags:
      - "v*.*.*"

jobs:
  build:
    strategy:
      matrix:
        platform: [ubuntu-latest, macos-latest, windows-latest]
    runs-on: ${{ matrix.platform }}

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 18

      - name: Setup Rust
        uses: dtolnay/rust-toolchain@stable

      # Linux-specific dependencies
      - name: Install Linux build dependencies
        if: runner.os == 'Linux'
        run: |
          sudo apt update
          sudo apt install -y \
            libwebkit2gtk-4.0-dev \
            libgtk-3-dev \
            libglib2.0-dev \
            libgobject-2.0-dev \
            libgio2.0-dev \
            libssl-dev \
            pkg-config \
            curl \
            wget \
            file \
            build-essential \
            libayatana-appindicator3-dev \
            librsvg2-dev
          echo "PKG_CONFIG_PATH=/usr/lib/x86_64-linux-gnu/pkgconfig:/usr/share/pkgconfig" >> $GITHUB_ENV

      # macOS-specific setup for notarization (no signing since user opted out)
      - name: Install macOS system dependencies
        if: runner.os == 'macOS'
        run: |
          brew install pkg-config cairo gtk+3 webkit2gtk

      - name: Install npm dependencies
        run: npm install

      - name: Tauri Build and Release
        uses: tauri-apps/tauri-action@v0
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          releaseId: ${{ github.event.release.id }}
          tagName: ${{ github.ref_name }}
          releaseName: "TerraCrypt Chat ${{ github.ref_name }}"
          releaseDraft: false
          prerelease: false
