name: Build Tauri App

on:
  push:
    tags:
      - "v*.*.*"

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20

      - name: Setup Rust
        uses: dtolnay/rust-toolchain@stable
        with:
          toolchain: stable

      - name: Install Complete GTK/GLib Stack
        run: |
          # First clean up any existing installations
          sudo apt-get remove -y libglib2.0-dev libgobject-2.0-dev libgio-2.0-dev || true
          sudo apt-get autoremove -y
          
          # Install complete development stack
          sudo apt-get update -y
          sudo apt-get install -y \
            libglib2.0-dev \
            libgirepository1.0-dev \
            libgobject-2.0-dev \
            libgio-2.0-dev \
            libgtk-3-dev \
            libwebkit2gtk-4.0-dev \
            libssl-dev \
            pkg-config \
            build-essential \
            libayatana-appindicator3-dev \
            librsvg2-dev

          # Force reinstall if files are missing
          if [ ! -f "/usr/lib/x86_64-linux-gnu/pkgconfig/glib-2.0.pc" ] || \
             [ ! -f "/usr/lib/x86_64-linux-gnu/pkgconfig/gobject-2.0.pc" ] || \
             [ ! -f "/usr/lib/x86_64-linux-gnu/pkgconfig/gio-2.0.pc" ]; then
            echo "::warning::Some .pc files missing, reinstalling..."
            sudo apt-get install --reinstall -y \
              libglib2.0-dev \
              libgobject-2.0-dev \
              libgio-2.0-dev
          fi

          # Set comprehensive environment variables
          echo "PKG_CONFIG_PATH=/usr/lib/x86_64-linux-gnu/pkgconfig:/usr/share/pkgconfig:/usr/local/lib/pkgconfig" >> $GITHUB_ENV
          echo "LD_LIBRARY_PATH=/usr/lib/x86_64-linux-gnu:/usr/local/lib" >> $GITHUB_ENV
          echo "GI_TYPELIB_PATH=/usr/lib/x86_64-linux-gnu/girepository-1.0" >> $GITHUB_ENV

      - name: Verify Installation
        run: |
          echo "=== Verification ==="
          echo "GLib version: $(pkg-config --modversion glib-2.0)"
          echo "GObject version: $(pkg-config --modversion gobject-2.0)"
          echo "GIO version: $(pkg-config --modversion gio-2.0)"
          echo "PKG_CONFIG_PATH: $PKG_CONFIG_PATH"
          echo "glib-2.0.pc: $(ls -la /usr/lib/x86_64-linux-gnu/pkgconfig/glib-2.0.pc 2>/dev/null || echo 'Not found')"
          echo "gobject-2.0.pc: $(ls -la /usr/lib/x86_64-linux-gnu/pkgconfig/gobject-2.0.pc 2>/dev/null || echo 'Not found')"
          echo "gio-2.0.pc: $(ls -la /usr/lib/x86_64-linux-gnu/pkgconfig/gio-2.0.pc 2>/dev/null || echo 'Not found')"
          
          pkg-config --exists glib-2.0 || (echo "::error::GLib not found!" && exit 1)
          pkg-config --exists gobject-2.0 || (echo "::error::GObject not found!" && exit 1)
          pkg-config --exists gio-2.0 || (echo "::error::GIO not found!" && exit 1)

      - name: Install npm dependencies
        run: npm install

      - name: Build Tauri App
        run: |
          export PKG_CONFIG_PATH=$PKG_CONFIG_PATH
          export LD_LIBRARY_PATH=$LD_LIBRARY_PATH
          export GI_TYPELIB_PATH=$GI_TYPELIB_PATH
          npm run tauri build

      - name: Upload artifacts
        uses: actions/upload-artifact@v4
        with:
          name: tauri-build
          path: src-tauri/target/release/
