name: Build Tauri App

on:
  push:
    tags:
      - "v*.*.*"

jobs:
  build:
    strategy:
      matrix:
        platform: [ubuntu-latest, macos-latest, windows-latest]
    runs-on: ${{ matrix.platform }}

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20

      - name: Setup Rust
        uses: dtolnay/rust-toolchain@stable
        with:
          toolchain: stable
          targets: x86_64-unknown-linux-gnu  # Only needed for Linux

      # Linux-specific setup
      - name: Install Linux dependencies
        if: runner.os == 'Linux'
        run: |
          sudo apt-get update -y
          sudo apt-get install -y \
            libwebkit2gtk-4.0-dev \
            libgtk-3-dev \
            libglib2.0-dev \
            libgirepository1.0-dev \
            libgobject-2.0-dev \
            libgio-2.0-dev \
            libssl-dev \
            pkg-config \
            build-essential \
            libayatana-appindicator3-dev \
            librsvg2-dev

          # Create symlinks to ensure pkg-config can find the files
          sudo ln -sf /usr/lib/x86_64-linux-gnu/pkgconfig/glib-2.0.pc /usr/share/pkgconfig/ || true
          sudo ln -sf /usr/lib/x86_64-linux-gnu/pkgconfig/gobject-2.0.pc /usr/share/pkgconfig/ || true
          sudo ln -sf /usr/lib/x86_64-linux-gnu/pkgconfig/gio-2.0.pc /usr/share/pkgconfig/ || true

          echo "PKG_CONFIG_PATH=/usr/lib/x86_64-linux-gnu/pkgconfig:/usr/share/pkgconfig" >> $GITHUB_ENV
          echo "LD_LIBRARY_PATH=/usr/lib/x86_64-linux-gnu" >> $GITHUB_ENV

      # macOS-specific setup
      - name: Install macOS dependencies
        if: runner.os == 'macOS'
        run: |
          brew update
          brew install pkg-config gtk+3 webkit2gtk librsvg
          brew link --overwrite gtk+3

      # Windows-specific setup
      - name: Install Windows dependencies
        if: runner.os == 'Windows'
        run: |
          choco install -y visualstudio2022-workload-vctools
          refreshenv

      - name: Verify dependencies
        run: |
          if [[ "$RUNNER_OS" == "Linux" ]]; then
            echo "=== Linux Verification ==="
            pkg-config --modversion glib-2.0 || echo "GLib not found"
            pkg-config --modversion gobject-2.0 || echo "GObject not found"
            pkg-config --modversion gio-2.0 || echo "GIO not found"
          elif [[ "$RUNNER_OS" == "macOS" ]]; then
            echo "=== macOS Verification ==="
            brew list gtk+3 || echo "GTK not found"
            brew list webkit2gtk || echo "WebKitGTK not found"
          else
            echo "=== Windows Verification ==="
            cl.exe /? > nul || echo "Visual Studio tools not found"
          fi

      - name: Install npm dependencies
        run: npm install

      - name: Build Tauri app
        env:
          PKG_CONFIG_PATH: ${{ runner.os == 'Linux' && '/usr/lib/x86_64-linux-gnu/pkgconfig:/usr/share/pkgconfig' || '' }}
          LD_LIBRARY_PATH: ${{ runner.os == 'Linux' && '/usr/lib/x86_64-linux-gnu' || '' }}
        run: npm run tauri build

      - name: Upload artifacts
        uses: actions/upload-artifact@v4
        with:
          name: tauri-build-${{ runner.os }}
          path: |
            src-tauri/target/release/*.deb
            src-tauri/target/release/*.AppImage
            src-tauri/target/release/*.tar.gz
            src-tauri/target/release/*.msi
            src-tauri/target/release/*.exe
