name: Tauri Cross-Platform Build

on:
  push:
    tags:
      - "v*.*.*"

jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-22.04, windows-latest, macos-latest]

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 18

      - name: Setup Rust
        uses: dtolnay/rust-toolchain@stable
        with:
          toolchain: stable
          targets: x86_64-unknown-linux-gnu

      - name: Install Linux dependencies
        if: matrix.os == 'ubuntu-22.04'
        run: |
          sudo apt-get update -y
          sudo apt-get install -y \
            build-essential \
            libssl-dev \
            libffi-dev \
            libmount-dev \
            zlib1g-dev \
            gettext \
            cmake \
            ninja-build \
            meson \
            libgtk-3-dev \
            libwebkit2gtk-4.1-dev \
            libsoup-3.0-dev \
            libayatana-appindicator3-dev \
            librsvg2-dev \
            patchelf \
            pkg-config

      - name: Install Windows dependencies
        if: matrix.os == 'windows-latest'
        run: |
          choco install -y nodejs.install
          choco install -y python --version=3.11.5
          choco install -y mingw

      - name: Install macOS dependencies
        if: matrix.os == 'macos-latest'
        run: |
          brew update
          brew upgrade cmake  # Upgrade outdated cmake
          brew install gtk+3 webkitgtk libsoup libayatana-appindicator3
          brew link --overwrite libayatana-appindicator3

      - name: Install npm dependencies
        run: npm install

      - name: Build Tauri app
        run: npm run tauri build

      - name: Upload artifacts
        if: success()
        uses: actions/upload-artifact@v4
        with:
          name: tauri-${{ matrix.os }}-build
          path: |
            src-tauri/target/release/*.deb
            src-tauri/target/release/*.AppImage
            src-tauri/target/release/*.msi
            src-tauri/target/release/*.dmg
            src-tauri/target/release/*.pkg
            src-tauri/target/release/*.zip
            src-tauri/target/release/*.tar.gz
